("YOS.DGO"
  ("mistycannon.o" "mistycannon")
  ("babak-with-cannon.o" "babak-with-cannon")
  ("target-racer-h.o" "target-racer-h")
  ("racer-part.o" "racer-part")
  ("racer.o" "racer")
  ("target-racer.o" "target-racer")
  ("collide-reaction-racer.o" "collide-reaction-racer")
  ("eichar-racer+0-ag.go" "eichar-racer+0")
  ("tpage-1119.go" "tpage-1119")
  ("blocking-plane.o" "blocking-plane")
  ("eichar-pole+0-ag.go" "eichar-pole+0")
  ("tpage-1332.go" "tpage-1332")
  ("tpage-1334.go" "tpage-1334")
  ("tpage-1333.go" "tpage-1333")
  ("tpage-1331.go" "tpage-1331")
  ("ef-plane-ag.go" "ef-plane")
  ("mistycannon-ag.go" "mistycannon")
  ("sack-ag.go" "sack")
  ("racer-ag.go" "racer")
  ("yosemite-vis.go" "yosemite-vis")
  )