("FOY.DGO"
  ("mistycannon.o" "mistycannon")
  ("babak-with-cannon.o" "babak-with-cannon")
  ("blocking-plane.o" "blocking-plane")
  ("target-racer-h.o" "target-racer-h")
  ("racer-part.o" "racer-part")
  ("racer.o" "racer")
  ("target-racer.o" "target-racer")
  ("racer-states.o" "racer-states")
  ("collide-reaction-racer.o" "collide-reaction-racer")
  ("eichar-racer+0-ag.go" "eichar-racer+0")
  ("blocking-plane.o" "blocking-plane")
  ("eichar-pole+0-ag.go" "eichar-pole+0")
  ("ef-plane-ag.go" "ef-plane")
  ("mistycannon-ag.go" "mistycannon")
  ("sack-ag.go" "sack")
  ("racer-ag.go" "racer")
  ("foyer.go" "foyer")
  )